# Generated by Django 5.2.5 on 2025-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
