# Generated by Django 5.2.5 on 2025-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feedbacks_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
