# Generated by Django 5.2.5 on 2025-09-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
