# Generated by Django 5.2.5 on 2025-09-12 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="feedbacks_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="likes_count",
        ),
    ]
