# Generated by Django 5.2.5 on 2025-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
