# Generated by Django 5.2.5 on 2025-09-11 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_post_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
