# Generated by Django 5.2.5 on 2025-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmsPenndingBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(unique=True)),
                ("code", models.CharField(blank=True, max_length=4, null=True)),
                ("phone", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
